spring.application.name=Student-Tracker
# Database
spring.datasource.url=jdbc:mysql://localhost/student_directory
spring.datasource.username=springstudent
spring.datasource.password=SpringStudent1@

springdoc.swagger-ui.path=ui.html
springdoc.api-docs.path=api-docs
